### ISSUE TITLE
로그인/회원가입 후 계속 회원가입 페이지로 이동

### ISSUE THREAD

**Issue by deeun** [woowsnu/Re-staurant#17]
## 이슈 상세 설명
> 회원가입 및 로그인 후 계속 회원가입 페이지로 이동해서 새로고침 해줘야함

## 이슈 발생한 위치, 파일명, 경로
발생경로 
- "/members" 
- "/mypage"

## 작업 상세 내용
- Auth Context 적용하여 수정 필요

**Comment by gun-0208** [comment]
로그인 후에 메인 페이지로 이동하게끔 세팅하면 될까요?? 
메인 페이지 url알려주시면 수정해놓겠습니다!

**Comment by deeun** [comment]
우선 프론트쪽에서 임시 수정해두었습니다. 라우터 이동 관련, 메인페이지 제작 진행 후 추후 다듬을 예정입니다. 확인 감사합니다 건님 😇
