### ISSUE TITLE
레스토랑 상세 정보 menuList, optionsList, reviewList 객체가 스트링으로 전달됨

### ISSUE THREAD

**Issue by woowsnu** [woowsnu/Re-staurant#65]
## 이슈 상세 설명

식당 상세페이지에서 이번에 추가해주신 메뉴리스트, 옵션리스트, 리뷰리스트가 아래와 같이 전체가 스트링으로 전달됩니다..!
```
    ....
    "menuList": "{[{menuName : 감자사리, menuPrice : 3,000원}, {menuName : 맥주, menuPrice : 5,000원}, {menuName : 닭도리탕, menuPrice : 30,000원}, {menuName : 국수사리, menuPrice : 2,000원}, {menuName : 공기밥, menuPrice : 2,000원}, {menuName : 소주, menuPrice : 4,000원}, {menuName : 버섯사리, menuPrice : 2,000원}, {menuName : 닭한마리, menuPrice : 25,000원}, {menuName : 떡사리, menuPrice : 1,000원}]}",
    "optionsList": "{[optionId : 2optionName : 주차iconUrl : http://static.naver.net/maps2/ic_endinfo2.png, isCheck : 1, orderCount : 1]}",
    "reviewList": "{[{ reviewIndex :8, reviewTitle : sdfsdfsdf, reviewContent : sdfsdfsdfsdfsdfsdf, email : test@test.com}]}"
>
```
프론트에서 이 데이터를 받아서 사용할 때, 저 부분이 json 형식이 아니기 때문에 JSON.Parse 적용이 되지 않고,
JSON.stringify 사용해 json 타입으로 만들려고하면 전체가 스트링으로 묶여버립니다.

 추가로 optionsList에는 각 항목이 쉼표로 분리되어 있어 위 방법을 적용하기 어려운 상황입니다.

* **api 요청 시 저 부분을 json 형식으로 보내줄수도 있을까요? 안된다면 아래 임시 해결 방법으로 진행하면 될 것 같긴합니다.**
* **optionsList 키-값 뒤에 쉼표 추가가 필요합니다. ex optionId : 2`,`optionName : 주차**

## 이슈 발생한 위치, 파일명, 경로

* API
/restaurant/restaurantDetail/{busId}

* front
/detail/{busId}

### 임시 해결 방안
우선 메뉴리스트 같은 경우에는 배열매서드 사용해서 큰따옴표 넣어주어 json 형식처럼 만든 뒤에는 사용 가능한 것으로 확인했습니다.
```
      let menuDataString = response.data.menuList
        .replaceAll('{m', '{"m')
        .replaceAll(':', '":"')
        .replaceAll(', m', '","m')
        .replaceAll('원}', '원"}')
        .slice(1)
        .slice(0, -1)
        .replaceAll(' ', '');
      const menuData = JSON.parse(menuDataString);
```

**Comment by gun-0208** [comment]
리스트안에 객체 전체가 string 한줄로 묶여서 파싱된다는 말씀이실까요?? 한번 확인해보겠습니다. 다시보니까 반환타입이 좀 잘못된 것 같긴하네요.

**Comment by woowsnu** [comment]
넵 우선 데이터 받은 것 그대로 콘솔 찍으면 이런식으로 나오고
![image](https://user-images.githubusercontent.com/105709187/190562235-fcce0f0a-88ad-4cfc-b3f0-5db9551d0f4b.png)

![image](https://user-images.githubusercontent.com/105709187/190562035-99ad6a65-fdb9-4923-8b1f-ee936a05be6c.png)

strigify하면 이렇게 전체가 묶입니다!
![image](https://user-images.githubusercontent.com/105709187/190562474-cc54d9fc-d7bf-44e7-b883-1363ab8a3205.png)

**Comment by gun-0208** [comment]
<img width="1084" alt="스크린샷 2022-09-16 오후 3 32 31" src="https://user-images.githubusercontent.com/67572011/190573104-0fbea805-a3c7-42c1-a581-782effdefbee.png">
DTO 파일 및 각 모델 중 N:1 맵핑으로 json serialization에서 무한순환참조 발생하는 부분 수정완료했습니다.
